version: '3.8'

services:
  frontend:
    build:
      context: ./reactfrontend
      dockerfile: dockerfile.frontend
    container_name: frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - my-network
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - mongodb-data:/data/db
  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile.backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/Lay-App
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
   mongodb-data: {}
