version: '3.8'

services:
  frontend:
    build:
      context: ./reactfrontend
      dockerfile: dockerfile.frontend
    container_name: frontend-cdexx
    ports:
      - "3000:3000"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.backend
    container_name: backend-cdexx
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/Lay-App
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "5020:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s


volumes:
  mongodb-data: {}
