version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - mongodb-data:/data/db
  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/Lay-App
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
   mongodb-data: {}
