version: '3.8'

services:
  frontend:
    build:
      context: ./reactfrontend
      dockerfile: dockerfile.frontend
    container_name: frontend-cdexx
    expose:
      - "3000"
    depends_on:
      - backend
    environment:
    - REACT_APP_API_URL=https://lai24b-k11.tekomits.my.id

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    expose:
      - "27017"
    volumes:
      - mongodb-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.backend
    container_name: backend-cdexx
    expose:
      - "4000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/Lay-App

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "5020:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend


volumes:
  mongodb-data: {}
